language: python
python:
# There seems to be some issue with pyp3 + psutil. Travis says
#   Error importing unittest: unable to load extension module [...]
#       /home/travis/virtualenv/pypy3-2.4.0/site-packages/psutil/_psutil_linux.pypy3-24.so: undefined symbol: PyModule_GetState
#  - "pypy3"
  - "pypy"
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install pybuilder
  - pip install coveralls
  - pyb install_dependencies
  
script: "pyb verify analyze -X"
after_success:
  - coveralls --verbose
